import React from "react";

export const useCardDatabase = () => {
  const avelhemCardList = [
    {
      Name: "Fire Avelhem",
      Stock: 4,
      Method: "Avelhem",
      CardId: 1,
    },
    {
      Name: "Water Avelhem",
      Stock: 4,
      Method: "Avelhem",
      CardId: 2,
    },
    {
      Name: "Wind Avelhem",
      Stock: 4,
      Method: "Avelhem",
      CardId: 3,
    },
    {
      Name: "Land Avelhem",
      Stock: 4,
      Method: "Avelhem",
      CardId: 4,
    },
    {
      Name: "Lightning Avelhem",
      Stock: 4,
      Method: "Avelhem",
      CardId: 5,
    },
    {
      Name: "Mana Avelhem",
      Stock: 4,
      Method: "Avelhem",
      CardId: 6,
    },
    {
      Name: "Metal Avelhem",
      Stock: 4,
      Method: "Avelhem",
      CardId: 7,
    },
    {
      Name: "Plant Avelhem",
      Stock: 4,
      Method: "Avelhem",
      CardId: 8,
    },
  ];

  const skillCardList = [
    //fire
    {
      Name: "Ignition Propulsion",
      Stock: 4,
      Aspect: "Fire",
      Method: "Standard",
      CardId: 1,
    },
    {
      Name: "Conflagration",
      Stock: 4,
      Aspect: "Fire",
      Method: "Resonant",
      CardId: 2,
    },
    {
      Name: "Blaze Of Glory",
      Stock: 4,
      Aspect: "Fire",
      Method: "Contingent",
      CardId: 3,
    },
    {
      Name: "Resplendence",
      Stock: 1,
      Aspect: "Fire",
      Method: "Burst",
      CardId: 4,
    },
    //water
    {
      Name: "Purification",
      Stock: 4,
      Aspect: "Water",
      Method: "Standard",
      CardId: 5,
    },
    {
      Name: "Frigid Breath",
      Stock: 4,
      Aspect: "Water",
      Method: "Resonant",
      CardId: 6,
    },
    {
      Name: "Healing Rain",
      Stock: 4,
      Aspect: "Water",
      Method: "Contingent",
      CardId: 7,
    },
    {
      Name: "Glacial Torrent",
      Stock: 1,
      Aspect: "Water",
      Method: "Burst",
      CardId: 8,
    },
    //wind
    {
      Name: "Aerial Impetus",
      Stock: 4,
      Aspect: "Wind",
      Method: "Standard",
      CardId: 9,
    },
    {
      Name: "Gale Conjuration",
      Stock: 4,
      Aspect: "Wind",
      Method: "Resonant",
      CardId: 10,
    },
    {
      Name: "Symphonic Screech",
      Stock: 4,
      Aspect: "Wind",
      Method: "Contingent",
      CardId: 11,
    },
    {
      Name: "Cataclysmic Tempest",
      Stock: 1,
      Aspect: "Wind",
      Method: "Burst",
      CardId: 12,
    },
    //land
    {
      Name: "Crystallization",
      Stock: 4,
      Aspect: "Land",
      Method: "Standard",
      CardId: 13,
    },
    {
      Name: "Upheaval",
      Stock: 4,
      Aspect: "Land",
      Method: "Resonant",
      CardId: 14,
    },
    {
      Name: "Pitfall Trap",
      Stock: 4,
      Aspect: "Land",
      Method: "Contingent",
      CardId: 15,
    },
    {
      Name: "Geomancy",
      Stock: 1,
      Aspect: "Land",
      Method: "Burst",
      CardId: 16,
    },
    //lightning
    {
      Name: "Chain Lightning",
      Stock: 4,
      Aspect: "Lightning",
      Method: "Standard",
      CardId: 17,
    },
    {
      Name: "Zip And Zap",
      Stock: 4,
      Aspect: "Lightning",
      Method: "Resonant",
      CardId: 18,
    },
    {
      Name: "Thunder Thaumaturge",
      Stock: 4,
      Aspect: "Lightning",
      Method: "Contingent",
      CardId: 19,
    },
    {
      Name: "Valiant Spark",
      Stock: 1,
      Aspect: "Lightning",
      Method: "Burst",
      CardId: 20,
    },
    //mana
    {
      Name: "Surge",
      Stock: 4,
      Aspect: "Mana",
      Method: "Standard",
      CardId: 21,
    },
    {
      Name: "Diffusion",
      Stock: 4,
      Aspect: "Mana",
      Method: "Resonant",
      CardId: 22,
    },
    {
      Name: "Aegis",
      Stock: 4,
      Aspect: "Mana",
      Method: "Contingent",
      CardId: 23,
    },
    {
      Name: "Disruption Field",
      Stock: 1,
      Aspect: "Mana",
      Method: "Burst",
      CardId: 24,
    },
    //metal
    {
      Name: "Magnetic Shockwave",
      Stock: 4,
      Aspect: "Metal",
      Method: "Standard",
      CardId: 25,
    },
    {
      Name: "Reinforce",
      Stock: 4,
      Aspect: "Metal",
      Method: "Resonant",
      CardId: 26,
    },
    {
      Name: "Frenzy Blade",
      Stock: 4,
      Aspect: "Metal",
      Method: "Contingent",
      CardId: 27,
    },
    {
      Name: "Arsenal Onslaught",
      Stock: 1,
      Aspect: "Metal",
      Method: "Burst",
      CardId: 28,
    },
    //plant
    {
      Name: "Sow And Reap",
      Stock: 4,
      Aspect: "Plant",
      Method: "Standard",
      CardId: 29,
    },
    {
      Name: "Efflorescence",
      Stock: 4,
      Aspect: "Plant",
      Method: "Resonant",
      CardId: 30,
    },
    {
      Name: "Viridian Grave",
      Stock: 4,
      Aspect: "Plant",
      Method: "Contingent",
      CardId: 31,
    },
    {
      Name: "Castle Of Thorns",
      Stock: 1,
      Aspect: "Plant",
      Method: "Burst",
      CardId: 32,
    },
    //sovereign
    {
      Name: "Heir’s Endeavor",
      Stock: 2,
      Aspect: "Sovereign",
      Method: "Standard",
      CardId: 33,
    },
    {
      Name: "Tea For Two",
      Stock: 2,
      Aspect: "Sovereign",
      Method: "Standard",
      CardId: 34,
    },
    {
      Name: "Unbridled Power",
      Stock: 2,
      Aspect: "Sovereign",
      Method: "Standard",
      CardId: 35,
    },
    {
      Name: "Dark Halo",
      Stock: 2,
      Aspect: "Sovereign",
      Method: "Standard",
      CardId: 36,
    },
    {
      Name: "Reminiscence",
      Stock: 2,
      Aspect: "Sovereign",
      Method: "Standard",
      CardId: 37,
    },
    {
      Name: "Foreshadow",
      Stock: 2,
      Aspect: "Sovereign",
      Method: "Standard",
      CardId: 38,
    },
    {
      Name: "Transmute",
      Stock: 2,
      Aspect: "Sovereign",
      Method: "Resonant",
      CardId: 39,
    },
    {
      Name: "Ambidexterity",
      Stock: 2,
      Aspect: "Sovereign",
      Method: "Resonant",
      CardId: 40,
    },
    {
      Name: "Providence",
      Stock: 2,
      Aspect: "Sovereign",
      Method: "Resonant",
      CardId: 41,
    },
    {
      Name: "Fervent Prayer",
      Stock: 2,
      Aspect: "Sovereign",
      Method: "Resonant",
      CardId: 42,
    },
    {
      Name: "Press The Attack",
      Stock: 2,
      Aspect: "Sovereign",
      Method: "Resonant",
      CardId: 43,
    },
    {
      Name: "Power At The Final Hour",
      Stock: 2,
      Aspect: "Sovereign",
      Method: "Contingent",
      CardId: 44,
    },
    {
      Name: "Fated Rivalry",
      Stock: 2,
      Aspect: "Sovereign",
      Method: "Contingent",
      CardId: 45,
    },
    {
      Name: "Match Made In Heaven",
      Stock: 2,
      Aspect: "Sovereign",
      Method: "Contingent",
      CardId: 46,
    },
    {
      Name: "Vengeful Legacy",
      Stock: 2,
      Aspect: "Sovereign",
      Method: "Contingent",
      CardId: 47,
    },
    {
      Name: "Black Business Card",
      Stock: 2,
      Aspect: "Sovereign",
      Method: "Contingent",
      CardId: 48,
    },
    {
      Name: "Coalescence",
      Stock: 1,
      Aspect: "Sovereign",
      Method: "Burst",
      CardId: 49,
    },
  ];

  return { avelhemCardList, skillCardList };
};
