import React from "react";

export const useDemoGameStates = () => {
  const getDemoGameState = (demo) => {
    switch (demo) {
      case "game":
        return {
          activatingUnit: [],
          activatingTarget: [],
          tactics: [],
          host: {
            bountyPoints: 0,
            skillRepertoire: [
              "01-01",
              "01-01",
              "01-01",
              "01-01",
              "01-02",
              "01-02",
              "01-02",
              "01-02",
              "01-03",
              "01-03",
              "01-03",
              "01-04",
              "02-01",
              "02-01",
              "02-01",
              "02-01",
              "02-02",
              "02-02",
              "02-02",
              "02-02",
              "02-03",
              "02-03",
              "02-04",
              "04-01",
              "04-01",
              "04-01",
              "04-01",
              "04-03",
              "04-03",
              "04-03",
              "04-03",
              "04-04",
              "07-01",
              "07-01",
              "07-01",
              "07-01",
              "07-02",
              "07-02",
              "07-02",
              "07-02",
              "07-03",
              "07-03",
              "07-03",
              "07-03",
              "07-04",
              "SA-02",
              "SA-02",
              "SA-03",
              "SA-03",
              "SA-04",
              "SA-04",
              "SB-01",
              "SB-01",
              "SB-03",
              "SB-03",
              "SB-04",
              "SB-04",
              "SB-05",
              "SB-05",
              "03-04",
            ],
            bountyUpgrades: {
              frontier: 0,
              coordination: 0,
              avelhem: 0,
              victory: 0,
              acquisition: 0,
              tactics: 0,
            },
            avelhemFloat: 0,
            avelhemVestige: [],
            skillHand: [],
            units: [],
            skillShattered: [],
            displayName: "Gold Player",
            score: 0,
            avelhemRepertoire: [
              1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 7, 7, 7, 7,
            ],
            skillVestige: [],
            skillFloat: 0,
            avelhemHand: [],
            fateDefiances: 3,
          },
          turnCount: 0,
          currentResolution: [],
          activatingResonator: [],
          guest: {
            avelhemFloat: 0,
            bountyPoints: 0,
            skillFloat: 0,
            displayName: "Silver Player",
            score: 0,
            avelhemRepertoire: [
              1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 7, 7, 7, 7,
            ],
            skillShattered: [],
            avelhemHand: [],
            fateDefiances: 3,
            skillVestige: [],
            skillHand: [],
            skillRepertoire: [
              "01-01",
              "01-01",
              "01-01",
              "01-01",
              "01-02",
              "01-02",
              "01-02",
              "01-02",
              "01-03",
              "01-03",
              "01-03",
              "01-04",
              "02-01",
              "02-01",
              "02-01",
              "02-01",
              "02-02",
              "02-02",
              "02-02",
              "02-02",
              "02-03",
              "02-03",
              "02-03",
              "02-03",
              "02-04",
              "04-01",
              "04-01",
              "04-01",
              "04-01",
              "04-03",
              "04-03",
              "04-03",
              "04-03",
              "04-04",
              "07-01",
              "07-01",
              "07-01",
              "07-01",
              "07-02",
              "07-02",
              "07-02",
              "07-02",
              "07-03",
              "07-03",
              "07-03",
              "07-03",
              "07-04",
              "SA-02",
              "SA-02",
              "SA-03",
              "SA-03",
              "SA-04",
              "SA-04",
              "SB-01",
              "SB-01",
              "SB-03",
              "SB-03",
              "SB-04",
              "SB-04",
              "03-04",
            ],
            bountyUpgrades: {
              coordination: 0,
              acquisition: 0,
              victory: 0,
              avelhem: 0,
              tactics: 0,
              frontier: 0,
            },
            units: [],
            avelhemVestige: [],
          },
          winObjective: 1,
          winner: null,
          zones:
            '[[{"id":0,"row":0,"column":0},{"id":1,"row":0,"column":1},{"id":2,"row":0,"column":2},{"id":3,"row":0,"column":3},{"id":4,"row":0,"column":4}],[{"id":5,"row":1,"column":0},{"id":6,"row":1,"column":1},{"id":7,"row":1,"column":2},{"id":8,"row":1,"column":3},{"id":9,"row":1,"column":4}],[{"id":10,"row":2,"column":0},{"id":11,"row":2,"column":1},{"id":12,"row":2,"column":2},{"id":13,"row":2,"column":3},{"id":14,"row":2,"column":4}],[{"id":15,"row":3,"column":0},{"id":16,"row":3,"column":1},{"id":17,"row":3,"column":2},{"id":18,"row":3,"column":3},{"id":19,"row":3,"column":4}],[{"id":20,"row":4,"column":0},{"id":21,"row":4,"column":1},{"id":22,"row":4,"column":2},{"id":23,"row":4,"column":3},{"id":24,"row":4,"column":4}],[{"id":25,"row":5,"column":0},{"id":26,"row":5,"column":1},{"id":27,"row":5,"column":2},{"id":28,"row":5,"column":3},{"id":29,"row":5,"column":4}],[{"id":30,"row":6,"column":0},{"id":31,"row":6,"column":1},{"id":32,"row":6,"column":2},{"id":33,"row":6,"column":3},{"id":34,"row":6,"column":4}],[{"id":35,"row":7,"column":0},{"id":36,"row":7,"column":1},{"id":37,"row":7,"column":2},{"id":38,"row":7,"column":3},{"id":39,"row":7,"column":4}],[{"id":40,"row":8,"column":0},{"id":41,"row":8,"column":1},{"id":42,"row":8,"column":2},{"id":43,"row":8,"column":3},{"id":44,"row":8,"column":4}],[{"id":45,"row":9,"column":0},{"id":46,"row":9,"column":1},{"id":47,"row":9,"column":2},{"id":48,"row":9,"column":3},{"id":49,"row":9,"column":4}]]',
          activatingSkill: [],
          turnPlayer: null,
          turnPhase: null,
        };

      case "fire":
        return {
          activatingUnit: [],
          host: {
            avelhemFloat: 0,
            score: 0,
            avelhemHand: [1, 1],
            fateDefiances: 0,
            units: [
              {
                row: 4,
                fever: 2,
                afflictions: {},
                player: "host",
                enhancements: { ravager: true },
                temporary: {},
                column: 0,
                unitIndex: 0,
                hp: 1,
                unitClass: "Fire Scion",
                virtue: 1,
                boosts: {},
              },
              null,
              {
                virtue: 1,
                player: "host",
                hp: 1,
                unitIndex: 2,
                afflictions: {},
                row: 3,
                unitClass: "Pawn",
                enhancements: {},
                boosts: {},
                temporary: {},
                column: 2,
              },
              {
                player: "host",
                unitIndex: 3,
                boosts: {},
                virtue: 1,
                row: 2,
                temporary: {},
                afflictions: { frostbite: 1 },
                unitClass: "Metal Scion",
                hp: 1,
                column: 1,
                enhancements: {},
              },
            ],
            skillShattered: [],
            skillFloat: 0,
            avelhemVestige: [1, 7, 5, 3],
            displayName: "Gold Player",
            skillHand: [
              "SX-01",
              "SX-01",
              "01-01",
              "01-02",
              "01-02",
              "SA-02",
              "01-04",
              "01-01",
              "02-03",
              "07-04",
            ],
            skillRepertoire: [
              "07-03",
              "02-03",
              "06-03",
              "01-02",
              "SA-03",
              "02-01",
              "SA-04",
              "08-02",
              "SC-04",
              "07-02",
              "01-03",
              "06-01",
              "07-03",
              "06-03",
              "SB-02",
              "02-01",
              "06-01",
              "06-01",
              "08-03",
              "06-04",
              "SB-01",
              "08-02",
              "08-01",
              "SB-02",
              "01-02",
              "08-03",
              "01-03",
              "07-03",
              "SB-05",
              "SC-04",
              "08-03",
              "01-01",
              "07-02",
              "SA-03",
              "07-03",
              "02-03",
              "06-03",
              "07-02",
              "02-03",
              "SA-04",
              "01-03",
              "02-01",
              "02-01",
              "01-01",
              "SC-03",
              "08-03",
              "06-03",
              "06-01",
              "SB-01",
              "01-03",
              "08-02",
              "05-01",
            ],
            avelhemRepertoire: [7, 2, 3, 3, 3, 6, 6, 6, 7, 2, 7, 2, 1, 6],
            skillVestige: [],
            bountyUpgrades: {
              avelhem: 0,
              acquisition: 0,
              coordination: 0,
              frontier: 0,
              victory: 0,
              tactics: 0,
            },
            bountyPoints: 0,
          },
          zones:
            '[[{"id":0,"row":0,"column":0,"player":"guest","unitIndex":5},{"id":1,"row":0,"column":1},{"id":2,"row":0,"column":2},{"id":3,"row":0,"column":3},{"id":4,"row":0,"column":4}],[{"id":5,"row":1,"column":0,"player":"guest","unitIndex":1},{"id":6,"row":1,"column":1,"player":null,"unitIndex":null},{"id":7,"row":1,"column":2,"player":null,"unitIndex":null},{"id":8,"row":1,"column":3,"player":"guest","unitIndex":0},{"id":9,"row":1,"column":4}],[{"id":10,"row":2,"column":0,"player":null,"unitIndex":null},{"id":11,"row":2,"column":1,"player":"host","unitIndex":3},{"id":12,"row":2,"column":2,"player":null,"unitIndex":null},{"id":13,"row":2,"column":3,"player":"guest","unitIndex":4},{"id":14,"row":2,"column":4}],[{"id":15,"row":3,"column":0,"player":null,"unitIndex":null},{"id":16,"row":3,"column":1,"player":null,"unitIndex":null},{"id":17,"row":3,"column":2,"player":"host","unitIndex":2},{"id":18,"row":3,"column":3,"player":null,"unitIndex":null},{"id":19,"row":3,"column":4,"player":null,"unitIndex":null}],[{"id":20,"row":4,"column":0,"player":"host","unitIndex":0},{"id":21,"row":4,"column":1,"player":null,"unitIndex":null},{"id":22,"row":4,"column":2,"player":null,"unitIndex":null},{"id":23,"row":4,"column":3,"player":null,"unitIndex":null},{"id":24,"row":4,"column":4}],[{"id":25,"row":5,"column":0,"player":"guest","unitIndex":3},{"id":26,"row":5,"column":1,"player":"guest","unitIndex":2},{"id":27,"row":5,"column":2,"player":null,"unitIndex":null},{"id":28,"row":5,"column":3,"player":null,"unitIndex":null},{"id":29,"row":5,"column":4}],[{"id":30,"row":6,"column":0,"player":null,"unitIndex":null},{"id":31,"row":6,"column":1,"player":null,"unitIndex":null},{"id":32,"row":6,"column":2,"player":null,"unitIndex":null},{"id":33,"row":6,"column":3},{"id":34,"row":6,"column":4,"player":null,"unitIndex":null}],[{"id":35,"row":7,"column":0},{"id":36,"row":7,"column":1,"player":null,"unitIndex":null},{"id":37,"row":7,"column":2},{"id":38,"row":7,"column":3},{"id":39,"row":7,"column":4}],[{"id":40,"row":8,"column":0,"player":null,"unitIndex":null},{"id":41,"row":8,"column":1},{"id":42,"row":8,"column":2},{"id":43,"row":8,"column":3},{"id":44,"row":8,"column":4}],[{"id":45,"row":9,"column":0},{"id":46,"row":9,"column":1},{"id":47,"row":9,"column":2},{"id":48,"row":9,"column":3},{"id":49,"row":9,"column":4}]]',
          turnPlayer: "host",
          guest: {
            avelhemHand: [],
            skillFloat: 0,
            score: 0,
            skillVestige: ["SX-01", "SX-01", "02-01"],
            bountyPoints: 0,
            bountyUpgrades: {
              tactics: 0,
              coordination: 0,
              victory: 0,
              avelhem: 0,
              acquisition: 0,
              frontier: 0,
            },
            skillShattered: ["02-04"],
            skillHand: [
              "01-03",
              "01-03",
              "01-01",
              "02-02",
              "02-01",
              "07-02",
              "04-03",
              "SC-04",
            ],
            avelhemRepertoire: [3, 2, 3, 3, 2, 2, 1, 7, 7, 7, 1, 4, 3, 1],
            avelhemVestige: [2, 4, 4, 7, 4, 1],
            fateDefiances: 0,
            units: [
              {
                row: 1,
                unitClass: "Water Scion",
                enhancements: { ward: 0 },
                boosts: {},
                temporary: {},
                unitIndex: 0,
                virtue: 1,
                player: "guest",
                hp: 1,
                column: 3,
                afflictions: { anathema: 0 },
              },
              {
                column: 0,
                afflictions: {},
                boosts: {},
                row: 1,
                unitClass: "Fire Scion",
                fever: 2,
                enhancements: {},
                player: "guest",
                virtue: 1,
                unitIndex: 1,
                hp: 1,
                temporary: {},
              },
              {
                unitClass: "Land Scion",
                enhancements: {},
                hp: 1,
                column: 1,
                row: 5,
                unitIndex: 2,
                afflictions: {},
                player: "guest",
                temporary: {},
                boosts: {},
                virtue: 1,
              },
              {
                virtue: 1,
                boosts: {},
                unitIndex: 3,
                unitClass: "Land Scion",
                row: 5,
                column: 0,
                enhancements: {},
                hp: 1,
                player: "guest",
                temporary: {},
                afflictions: {},
              },
              {
                temporary: {},
                row: 2,
                enhancements: {},
                virtue: 1,
                hp: 1,
                unitIndex: 4,
                column: 3,
                player: "guest",
                unitClass: "Pawn",
                boosts: {},
                afflictions: {},
              },
              {
                virtue: 1,
                boosts: {},
                row: 0,
                temporary: {},
                unitClass: "Pawn",
                player: "guest",
                column: 0,
                hp: 1,
                unitIndex: 5,
                afflictions: {},
                enhancements: {},
              },
            ],
            displayName: "Silver Player",
            avelhemFloat: 0,
            skillRepertoire: [
              "07-03",
              "07-03",
              "02-03",
              "02-01",
              "07-01",
              "SA-02",
              "07-03",
              "07-01",
              "SB-01",
              "07-02",
              "01-02",
              "SB-04",
              "01-04",
              "01-01",
              "01-02",
              "SA-02",
              "SB-03",
              "02-03",
              "04-04",
              "04-03",
              "SA-03",
              "02-03",
              "02-01",
              "08-01",
              "07-02",
              "05-01",
              "05-01",
              "02-02",
              "02-02",
              "04-01",
              "07-01",
              "04-03",
              "SA-04",
              "SA-03",
              "01-03",
              "01-01",
              "04-03",
              "07-01",
              "SB-03",
              "SB-01",
              "07-04",
              "07-02",
              "01-02",
              "02-02",
              "07-03",
              "04-01",
              "SA-04",
              "SB-04",
              "01-01",
              "08-01",
            ],
          },
          turnPhase: "Execution",
          tactics: [
            { limit: 1, stock: 1, face: "Invoke" },
            { stock: 3, face: "Mobilize", limit: 3 },
          ],
          activatingTarget: [],
          winObjective: 1,
          activatingSkill: [],
          turnCount: 9,
          winner: null,
          currentResolution: [{ resolution: "Execution Phase" }],
          activatingResonator: [],
        };

      default:
        return;
    }
  };

  return { getDemoGameState };
};
