import React from "react";
import { useSelector, useDispatch } from "react-redux";

export const useDemoGameStates = () => {
  const { demoGuide } = useSelector((state) => state.demoGuide);
  const { demoCount } = useSelector((state) => state.demoCount);

  const getDemoGameState = (demo) => {
    switch (demo) {
      case "game":
        return {
          activatingUnit: [],
          activatingTarget: [],
          tactics: [],
          host: {
            bountyPoints: 0,
            skillRepertoire: [
              "01-01",
              "01-01",
              "01-01",
              "01-01",
              "01-02",
              "01-02",
              "01-02",
              "01-02",
              "01-03",
              "01-03",
              "01-03",
              "01-04",
              "02-01",
              "02-01",
              "02-01",
              "02-01",
              "02-02",
              "02-02",
              "02-02",
              "02-02",
              "02-03",
              "02-03",
              "02-04",
              "04-01",
              "04-01",
              "04-01",
              "04-01",
              "04-03",
              "04-03",
              "04-03",
              "04-03",
              "04-04",
              "07-01",
              "07-01",
              "07-01",
              "07-01",
              "07-02",
              "07-02",
              "07-02",
              "07-02",
              "07-03",
              "07-03",
              "07-03",
              "07-03",
              "07-04",
              "SA-02",
              "SA-02",
              "SA-03",
              "SA-03",
              "SA-04",
              "SA-04",
              "SB-01",
              "SB-01",
              "SB-03",
              "SB-03",
              "SB-04",
              "SB-04",
              "SB-05",
              "SB-05",
              "03-04",
            ],
            bountyUpgrades: {
              frontier: 0,
              coordination: 0,
              avelhem: 0,
              victory: 0,
              acquisition: 0,
              tactics: 0,
              burst: 0,
            },
            avelhemFloat: 0,
            avelhemVestige: [],
            skillHand: [],
            units: [],
            skillShattered: [],
            displayName: "Gold Sovereign",
            score: 0,
            avelhemRepertoire: [
              1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 7, 7, 7, 7,
            ],
            skillVestige: [],
            skillFloat: 0,
            avelhemHand: [],
            fateDefiance: 3,
          },
          turnCount: 0,
          currentResolution: [],
          activatingResonator: [],
          guest: {
            avelhemFloat: 0,
            bountyPoints: 0,
            skillFloat: 0,
            displayName: "Silver Sovereign",
            score: 0,
            avelhemRepertoire: [
              1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 7, 7, 7, 7,
            ],
            skillShattered: [],
            avelhemHand: [],
            fateDefiance: 3,
            skillVestige: [],
            skillHand: [],
            skillRepertoire: [
              "01-01",
              "01-01",
              "01-01",
              "01-01",
              "01-02",
              "01-02",
              "01-02",
              "01-02",
              "01-03",
              "01-03",
              "01-03",
              "01-04",
              "02-01",
              "02-01",
              "02-01",
              "02-01",
              "02-02",
              "02-02",
              "02-02",
              "02-02",
              "02-03",
              "02-03",
              "02-03",
              "02-03",
              "02-04",
              "04-01",
              "04-01",
              "04-01",
              "04-01",
              "04-03",
              "04-03",
              "04-03",
              "04-03",
              "04-04",
              "07-01",
              "07-01",
              "07-01",
              "07-01",
              "07-02",
              "07-02",
              "07-02",
              "07-02",
              "07-03",
              "07-03",
              "07-03",
              "07-03",
              "07-04",
              "SA-02",
              "SA-02",
              "SA-03",
              "SA-03",
              "SA-04",
              "SA-04",
              "SB-01",
              "SB-01",
              "SB-03",
              "SB-03",
              "SB-04",
              "SB-04",
              "03-04",
            ],
            bountyUpgrades: {
              coordination: 0,
              acquisition: 0,
              victory: 0,
              avelhem: 0,
              tactics: 0,
              frontier: 0,
              burst: 0,
            },
            units: [],
            avelhemVestige: [],
          },
          winObjective: 1,
          winner: null,
          zones:
            '[[{"id":0,"row":0,"column":0},{"id":1,"row":0,"column":1},{"id":2,"row":0,"column":2},{"id":3,"row":0,"column":3},{"id":4,"row":0,"column":4}],[{"id":5,"row":1,"column":0},{"id":6,"row":1,"column":1},{"id":7,"row":1,"column":2},{"id":8,"row":1,"column":3},{"id":9,"row":1,"column":4}],[{"id":10,"row":2,"column":0},{"id":11,"row":2,"column":1},{"id":12,"row":2,"column":2},{"id":13,"row":2,"column":3},{"id":14,"row":2,"column":4}],[{"id":15,"row":3,"column":0},{"id":16,"row":3,"column":1},{"id":17,"row":3,"column":2},{"id":18,"row":3,"column":3},{"id":19,"row":3,"column":4}],[{"id":20,"row":4,"column":0},{"id":21,"row":4,"column":1},{"id":22,"row":4,"column":2},{"id":23,"row":4,"column":3},{"id":24,"row":4,"column":4}],[{"id":25,"row":5,"column":0},{"id":26,"row":5,"column":1},{"id":27,"row":5,"column":2},{"id":28,"row":5,"column":3},{"id":29,"row":5,"column":4}],[{"id":30,"row":6,"column":0},{"id":31,"row":6,"column":1},{"id":32,"row":6,"column":2},{"id":33,"row":6,"column":3},{"id":34,"row":6,"column":4}],[{"id":35,"row":7,"column":0},{"id":36,"row":7,"column":1},{"id":37,"row":7,"column":2},{"id":38,"row":7,"column":3},{"id":39,"row":7,"column":4}],[{"id":40,"row":8,"column":0},{"id":41,"row":8,"column":1},{"id":42,"row":8,"column":2},{"id":43,"row":8,"column":3},{"id":44,"row":8,"column":4}],[{"id":45,"row":9,"column":0},{"id":46,"row":9,"column":1},{"id":47,"row":9,"column":2},{"id":48,"row":9,"column":3},{"id":49,"row":9,"column":4}]]',
          activatingSkill: [],
          turnPlayer: null,
          turnPhase: null,
          skipAscensionTrigger: true,
        };

      case "learn-overview":
        return {
          winner: null,
          activatingSkill: [],
          winObjective: 1,
          turnPlayer: null,
          activatingTarget: [],
          activatingResonator: [],
          zones:
            '[[{"id":0,"row":0,"column":0},{"id":1,"row":0,"column":1},{"id":2,"row":0,"column":2},{"id":3,"row":0,"column":3},{"id":4,"row":0,"column":4}],[{"id":5,"row":1,"column":0},{"id":6,"row":1,"column":1},{"id":7,"row":1,"column":2},{"id":8,"row":1,"column":3},{"id":9,"row":1,"column":4}],[{"id":10,"row":2,"column":0},{"id":11,"row":2,"column":1},{"id":12,"row":2,"column":2},{"id":13,"row":2,"column":3},{"id":14,"row":2,"column":4}],[{"id":15,"row":3,"column":0},{"id":16,"row":3,"column":1},{"id":17,"row":3,"column":2},{"id":18,"row":3,"column":3},{"id":19,"row":3,"column":4}],[{"id":20,"row":4,"column":0},{"id":21,"row":4,"column":1},{"id":22,"row":4,"column":2},{"id":23,"row":4,"column":3},{"id":24,"row":4,"column":4}],[{"id":25,"row":5,"column":0},{"id":26,"row":5,"column":1},{"id":27,"row":5,"column":2},{"id":28,"row":5,"column":3},{"id":29,"row":5,"column":4}],[{"id":30,"row":6,"column":0},{"id":31,"row":6,"column":1},{"id":32,"row":6,"column":2},{"id":33,"row":6,"column":3},{"id":34,"row":6,"column":4}],[{"id":35,"row":7,"column":0},{"id":36,"row":7,"column":1},{"id":37,"row":7,"column":2},{"id":38,"row":7,"column":3},{"id":39,"row":7,"column":4}],[{"id":40,"row":8,"column":0},{"id":41,"row":8,"column":1},{"id":42,"row":8,"column":2},{"id":43,"row":8,"column":3},{"id":44,"row":8,"column":4}],[{"id":45,"row":9,"column":0},{"id":46,"row":9,"column":1},{"id":47,"row":9,"column":2},{"id":48,"row":9,"column":3},{"id":49,"row":9,"column":4}]]',
          host: {
            skillRepertoire: [
              "02-01",
              "02-01",
              "02-01",
              "02-01",
              "02-03",
              "02-03",
              "02-03",
              "02-03",
              "02-04",
              "04-01",
              "04-01",
              "04-02",
              "04-02",
              "04-03",
              "04-03",
              "04-03",
              "04-03",
              "06-03",
              "06-03",
              "06-03",
              "06-03",
              "06-04",
              "07-02",
              "07-02",
              "07-02",
              "07-02",
              "07-03",
              "07-03",
              "07-03",
              "07-03",
              "07-04",
              "08-01",
              "08-01",
              "08-01",
              "08-01",
              "08-02",
              "08-02",
              "08-02",
              "08-02",
              "08-03",
              "08-03",
              "08-03",
              "08-03",
              "08-04",
              "SA-01",
              "SA-01",
              "SA-04",
              "SA-04",
              "SB-01",
              "SB-01",
              "SB-02",
              "SB-02",
              "SB-04",
              "SB-05",
              "SC-01",
              "SC-01",
              "SC-03",
              "SC-03",
              "SC-05",
              "SC-05",
            ],
            skillFloat: 0,
            score: 0,
            avelhemVestige: [],
            fateDefiance: 3,
            avelhemFloat: 0,
            avelhemHand: [],
            bountyUpgrades: {
              coordination: 0,
              frontier: 0,
              avelhem: 0,
              acquisition: 0,
              victory: 0,
              tactics: 0,
              burst: 0,
            },
            units: [],
            skillHand: [],
            avelhemRepertoire: [
              2, 2, 2, 2, 4, 4, 4, 4, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8,
            ],
            skillVestige: [],
            skillShattered: [],
            bountyPoints: 0,
            displayName: "Gold Player",
          },
          turnCount: 0,
          tactics: [],
          guest: {
            score: 0,
            avelhemHand: [],
            avelhemRepertoire: [
              1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 7, 7, 8, 8,
            ],
            avelhemFloat: 0,
            skillFloat: 0,
            skillHand: [],
            skillRepertoire: [
              "01-01",
              "01-01",
              "01-01",
              "01-01",
              "01-02",
              "01-02",
              "01-02",
              "01-02",
              "01-03",
              "01-03",
              "01-03",
              "01-04",
              "02-01",
              "02-01",
              "02-01",
              "02-01",
              "02-02",
              "02-02",
              "02-02",
              "02-02",
              "02-03",
              "02-03",
              "02-03",
              "02-03",
              "02-04",
              "03-04",
              "04-01",
              "04-01",
              "04-01",
              "04-01",
              "04-03",
              "04-03",
              "04-03",
              "04-03",
              "04-04",
              "07-01",
              "07-01",
              "07-01",
              "07-03",
              "07-02",
              "07-02",
              "07-02",
              "07-02",
              "07-03",
              "07-03",
              "07-04",
              "SA-02",
              "SA-02",
              "SA-03",
              "SA-03",
              "SA-04",
              "SA-04",
              "SB-01",
              "SB-01",
              "SB-03",
              "SB-03",
              "SB-04",
              "SB-04",
              "SB-05",
              "SB-05",
            ],
            fateDefiance: 3,
            bountyPoints: 0,
            avelhemVestige: [],
            units: [],
            bountyUpgrades: {
              tactics: 0,
              victory: 0,
              acquisition: 0,
              coordination: 0,
              frontier: 0,
              avelhem: 0,
              burst: 0,
            },
            skillShattered: [],
            skillVestige: [],
            displayName: "Silver Player",
          },
          activatingUnit: [],
          turnPhase: null,
          currentResolution: [],
          skipAscensionTrigger: true,
        };

      case "classes":
        return {
          turnCount: 0,
          activatingUnit: [],
          turnPlayer: "host",
          currentResolution: [{ resolution: " " }],
          activatingTarget: [],
          activatingResonator: [],
          activatingSkill: [],
          guest: {
            score: 0,
            units: [
              null,
              {
                row: 3,
                afflictions: {},
                player: "guest",
                enhancements: {},
                unitClass: "Pawn",
                boosts: {},
                aether: 1,
                column: 2,
                hp: 1,
                temporary: {},
                unitIndex: 1,
              },
              null,
            ],
            displayName: "Silver Sovereign",
            avelhemVestige: [],
            avelhemHand: [],
            bountyUpgrades: {
              coordination: 0,
              tactics: 0,
              frontier: 0,
              acquisition: 0,
              victory: 0,
              avelhem: 0,
              burst: 0,
            },
            avelhemFloat: 0,
            avelhemRepertoire: [],
            skillShattered: [],
            bountyPoints: 3,
            fateDefiance: 6,
            skillHand: [],
            skillFloat: 0,
            skillVestige: [],
            skillRepertoire: [],
          },
          zones:
            '[[{"id":0,"row":0,"column":0},{"id":1,"row":0,"column":1},{"id":2,"row":0,"column":2},{"id":3,"row":0,"column":3},{"id":4,"row":0,"column":4}],[{"id":5,"row":1,"column":0},{"id":6,"row":1,"column":1},{"id":7,"row":1,"column":2},{"id":8,"row":1,"column":3},{"id":9,"row":1,"column":4}],[{"id":10,"row":2,"column":0},{"id":11,"row":2,"column":1},{"id":12,"row":2,"column":2},{"id":13,"row":2,"column":3},{"id":14,"row":2,"column":4}],[{"id":15,"row":3,"column":0,"player":null,"unitIndex":null},{"id":16,"row":3,"column":1},{"id":17,"row":3,"column":2,"player":"guest","unitIndex":1},{"id":18,"row":3,"column":3},{"id":19,"row":3,"column":4,"player":null,"unitIndex":null}],[{"id":20,"row":4,"column":0},{"id":21,"row":4,"column":1},{"id":22,"row":4,"column":2},{"id":23,"row":4,"column":3},{"id":24,"row":4,"column":4}],[{"id":25,"row":5,"column":0},{"id":26,"row":5,"column":1},{"id":27,"row":5,"column":2},{"id":28,"row":5,"column":3,"player":null,"unitIndex":null},{"id":29,"row":5,"column":4}],[{"id":30,"row":6,"column":0,"player":"host","unitIndex":0},{"id":31,"row":6,"column":1,"player":"host","unitIndex":1},{"id":32,"row":6,"column":2,"player":"host","unitIndex":2},{"id":33,"row":6,"column":3,"player":"host","unitIndex":3},{"id":34,"row":6,"column":4,"player":"host","unitIndex":4}],[{"id":35,"row":7,"column":0,"player":null,"unitIndex":null},{"id":36,"row":7,"column":1,"player":"host","unitIndex":5},{"id":37,"row":7,"column":2,"player":"host","unitIndex":6},{"id":38,"row":7,"column":3,"player":"host","unitIndex":7},{"id":39,"row":7,"column":4,"player":null,"unitIndex":null}],[{"id":40,"row":8,"column":0},{"id":41,"row":8,"column":1},{"id":42,"row":8,"column":2},{"id":43,"row":8,"column":3},{"id":44,"row":8,"column":4}],[{"id":45,"row":9,"column":0},{"id":46,"row":9,"column":1},{"id":47,"row":9,"column":2},{"id":48,"row":9,"column":3},{"id":49,"row":9,"column":4}]]',
          tactics: [],
          winner: null,
          host: {
            skillVestige: [],
            skillRepertoire: [],
            avelhemVestige: [],
            bountyUpgrades: {
              tactics: 0,
              coordination: 0,
              acquisition: 0,
              avelhem: 0,
              frontier: 0,
              victory: 0,
              burst: 0,
            },
            units: [
              {
                unitClass: "Fire Scion",
                hp: 1,
                boosts: {},
                unitIndex: 0,
                column: 0,
                enhancements: {},
                row: 6,
                afflictions: {},
                temporary: {},
                player: "host",
                aether: 1,
              },
              {
                enhancements: {},
                row: 6,
                temporary: {},
                hp: 1,
                boosts: {},
                column: 1,
                player: "host",
                unitClass: "Water Scion",
                unitIndex: 1,
                aether: 1,
                afflictions: {},
              },
              {
                unitClass: "Wind Scion",
                column: 2,
                unitIndex: 2,
                player: "host",
                hp: 1,
                enhancements: {},
                temporary: {},
                row: 6,
                afflictions: {},
                boosts: {},
                aether: 1,
              },
              {
                row: 6,
                afflictions: {},
                player: "host",
                aether: 1,
                hp: 1,
                temporary: {},
                column: 3,
                unitIndex: 3,
                boosts: {},
                unitClass: "Land Scion",
                enhancements: {},
              },
              {
                column: 4,
                player: "host",
                temporary: {},
                unitIndex: 4,
                boosts: {},
                aether: 1,
                hp: 1,
                enhancements: {},
                row: 6,
                unitClass: "Lightning Scion",
                afflictions: {},
              },
              {
                boosts: {},
                enhancements: {},
                unitIndex: 5,
                temporary: {},
                aether: 1,
                row: 7,
                player: "host",
                unitClass: "Mana Scion",
                afflictions: {},
                column: 1,
                hp: 1,
              },
              {
                unitClass: "Metal Scion",
                temporary: {},
                enhancements: {},
                aether: 1,
                afflictions: {},
                column: 2,
                player: "host",
                boosts: {},
                unitIndex: 6,
                hp: 1,
                row: 7,
              },
              {
                afflictions: {},
                temporary: {},
                column: 3,
                row: 7,
                enhancements: {},
                unitClass: "Plant Scion",
                unitIndex: 7,
                aether: 1,
                hp: 1,
                player: "host",
                boosts: {},
              },
            ],
            score: 0,
            displayName: "",
            avelhemFloat: 0,
            skillFloat: 0,
            skillShattered: [],
            bountyPoints: 8,
            skillHand: [],
            avelhemHand: [],
            avelhemRepertoire: [],
            fateDefiance: 6,
          },
          turnPhase: "Class Exhibit",
          winObjective: 1,
        };

      default:
        return;
    }
  };

  return { getDemoGameState };
};
